# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stirsdag
email: eplehans@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stiløping. Lillomarka. Oslo. Fast runde. 12km. 550 høydemeter. Hver tirsdag. Hele året. Kom som du er. Snakketempo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stirsdag.no" # the base hostname & protocol for your site, e.g. http://example.com
seo_keywords: Terrengløping, Oslo, Stiløping, Trail running, Sky Blazers
slogan: bedre enn lørdag

# Build settings
markdown: kramdown
destination: ./docs

google_analytics: UA-107726023-1

# Sass settings
sass:
  sass_dir: style
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
