title: Stirsdag
email: eplehans@gmail.com  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stirsdag.no" # the base hostname & protocol for your site, e.g. http://example.com
seo_keywords: Terrengløping, Oslo, Stiløping, Trail running, Sky Blazers
slogan: bedre enn lørdag

# Build settings
markdown: kramdown
destination: ./docs

google_analytics: UA-107726023-1

# Sass settings
sass:
  sass_dir: style
  style: compressed